CREATE TABLE IF NOT EXISTS symbols (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  char_code VARCHAR(10) NOT NULL UNIQUE,
  description VARCHAR(150) DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS dates (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  date DATE NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS rates (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  currency_id BIGINT NOT NULL,
  date_id BIGINT NOT NULL,
  rate DECIMAL(20, 5) NOT NULL,
  CONSTRAINT fk_rates_currency FOREIGN KEY (currency_id) REFERENCES symbols (id) ON DELETE CASCADE,
  CONSTRAINT fk_rates_date FOREIGN KEY (date_id) REFERENCES dates (id) ON DELETE CASCADE
);